name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4
  flutter: 3.38.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_weaver:
  flutter_crystalline:
    git:
      url: https://github.com/easazade/crystalline.git
      path: packages/flutter_crystalline
      ref: 027dee2
  dart_mappable: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1  
  weaver_builder:  
  flutter_lints: ^5.0.0
  crystalline_builder:
    git:
      url: https://github.com/easazade/crystalline.git
      path: packages/crystalline_builder
      ref: 027dee2
  dart_mappable_builder: ^4.6.4

dependency_overrides:    
  flutter_crystalline:
    git:
      url: https://github.com/easazade/crystalline.git
      path: packages/flutter_crystalline   
      ref: 027dee2
  crystalline:
    git:
      url: https://github.com/easazade/crystalline.git
      path: packages/crystalline   
      ref: 027dee2

flutter:

  uses-material-design: true