name: weaver

packages:
  - packages/*
  - packages/weaver/example

command:
  bootstrap:
    runPubGetInParallel: true
  version:
    linkToCommits: false     # disables commit links in generated changelog

scripts:
  format:
    run: dart format --set-exit-if-changed .
    
  check:
    run: melos exec -c 1 --ignore="example" -- "dart analyze"

  fix:
    run: melos exec -c 1 --ignore="example" -- "dart fix --apply"

  test:
    run: melos exec -c 1 --ignore="example" --ignore="weaver_builder" -- "flutter test --coverage"

  test:coverage:
    run: |
      melos exec -c 1 --scope="weaver" -- "dart test --coverage=coverage" &&
      melos exec -c 1 --scope="flutter_weaver" -- "flutter test --coverage"

  gen:
    run: | 
      melos exec -c 1 --scope="example" -- "flutter pub run build_runner build -d" &&
      melos exec -c 1 --scope="flutter_weaver" -- "flutter pub run build_runner build -d" &&
      melos exec -c 1 --scope="weaver" -- "flutter pub run build_runner build -d"


