name: weaver

packages:
  - packages/*
  - example/

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  format:
    run: dart format --set-exit-if-changed .
    
  analyze:
    run: melos exec -c 1 -- "dart analyze"

  test:
    run: melos exec -c 1 -- "flutter test"

  gen:
    run: melos exec -c 1 --scope="example" -- "dart run build_runner build -d"

