name: weaver
description: "Best dependency injection library for Flutter"
version: 0.2.1
homepage: https://pub.dev/packages/weaver
issue_tracker: https://github.com/easazade/weaver/issues


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.18.0  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
