import 'dart:async';

import 'package:collection/collection.dart';
import 'package:weaver/src/base/dependency_map.dart';
import 'package:weaver/src/base/named.dart';
import 'package:weaver/src/base/scope.dart';
import 'package:weaver/src/base/scope_handlers/scope_handler.dart';
import 'package:weaver/src/utils/log.dart';
import 'package:weaver/src/utils/observable.dart';

import 'dependency.dart';
import 'scope_handlers/single_scope_handler.dart';

/// default instance of [Weaver]
final weaver = Weaver();

/// This is a short hand function for weaver.get\<T\>().
/// Keep in mind This function only makes request to the default global instance of weaver.
///
/// for example below is wrong:
/// ```dart
/// final newWeaver = Weaver();
/// newWeaver.register('my name');
///
/// final myName = inject<String>(); // throws an exception since 'my name' is not registered in global instance of weaver
/// ```
T inject<T extends Object>({final String? name}) => weaver.get<T>(name: name);

/// This is a short hand function for weaver.getAsync\<T\>().
/// Keep in mind This function only makes request to the default global instance of weaver.
Future<T> injectAsync<T extends Object>() => weaver.getAsync<T>();

/// The main dependency injection container for Weaver.
///
/// [Weaver] manages the registration, retrieval, and lifecycle of dependency objects.
/// It supports global registrations, named dependencies, sessions, and scopes.
///
/// You can observe changes in registrations by adding an observer using [addObserver].
class Weaver extends Observable {
  /// Creates a new [Weaver] instance.
  Weaver();

  final _dependencyMap = DependencyMap();
  final _scopeHandlers = <ScopeHandler>[];

  /// Type-safe access to named dependencies generated by `weaver_builder`.
  late final named = WeaverNamed(weaverInstance: this);

  /// The currently active scopes in this [Weaver] instance.
  Iterable<Scope> get scopes => _scopeHandlers.map((final e) => e.currentScope).nonNulls;

  /// Whether to allow re-registering an object with the same [DependencyKey].
  /// Useful for testing to swap real implementations with mocks.
  var allowReassignment = false;

  /// Registers a dependency [instance] of type [T].
  ///
  /// [name] can be used to distinguish between multiple instances of the same type.
  /// [session] can be used to group dependencies that should be cleared together.
  void register<T extends Object>(final T instance, {final String? name, final String? session}) {
    if (T.toString() == 'Object') {
      throw WeaverException('T is Object. Cannot register object of the exact type of "Object"');
    }
    log('Registering object of type $T');

    final dependencyKey = DependencyKey(type: T, name: name);

    if (isRegistered<T>() && !allowReassignment) {
      throw WeaverException(
        'Cannot register object of $dependencyKey because there is an instance already registered',
      );
    }
    if (_dependencyMap.containsKey(dependencyKey)) {
      final dependency = (_dependencyMap.find(dependencyKey)! as Dependency<T>);
      dependency.value = instance;
    } else {
      _dependencyMap.set(dependencyKey, Dependency<T>.value(instance), session: session);
    }
    notifyObservers();
  }

  /// Registers an object if it is not already registered.
  ///
  /// If an object with the same type and name is already registered, this method does nothing.
  void registerIfIsNot<T extends Object>(final T instance, {final String? name, final String? session}) {
    if (!isRegistered<T>(name: name)) {
      register<T>(instance, name: name, session: session);
    }
  }

  /// Unregisters a dependency object by its type [T] or [name].
  void unregister<T extends Object>({Type? type, final String? name}) {
    if (type != null && T.toString() != 'Object' && type.toString() != T.toString()) {
      throw WeaverException(
        'calling unregister argument and passing conflicting arguments for the type of the '
        'object that needs to be unregistered is forbidden!, please specify the type correctly only using'
        'generic type argument or value argument. eg: either call weaver.unregister<TYPE>() or weaver.unregister(type: type). '
        'calling weaver.unregister<TYPE_1>(type: TYPE_2) is forbidden',
      );
    }
    type = type ?? T;

    if (name == null && type.toString() == 'Object') {
      throw WeaverException(
        'Type or name is required to unregister the dependency object. passed type of "$type" is not accepted',
      );
    } else if (name != null && type.toString() == 'Object') {
      _dependencyMap.removeWhere((final dependencyKey) => dependencyKey.name == name);
      notifyObservers();
    } else {
      final dependencyKey = DependencyKey(type: type, name: name);
      if (isRegistered(type: type, name: name)) {
        _dependencyMap.remove(dependencyKey);
      } else {
        log('⚠️ Tried to unregister an object that is not registered. '
            'There is no object registered with type: $type ${name != null ? "and name:$name" : ""}');
      }
      notifyObservers();
    }
  }

  /// Returns true if a dependency of type [T] (and optionally [name]) is registered.
  bool isRegistered<T extends Object>({Type? type, final String? name}) {
    type = type ?? T;

    if (type.toString() == 'Object') {
      return _dependencyMap.keys.firstWhereOrNull((final key) => key.name == name) != null;
    } else {
      final dependencyKey = DependencyKey(type: type, name: name);
      return _dependencyMap.containsKey(dependencyKey) && _dependencyMap.hasValue(dependencyKey);
    }
  }

  /// Registers a lazy dependency that will be instantiated when first requested.
  void registerLazy<T extends Object>(final T Function() callback, {final String? name}) {
    final dependencyKey = DependencyKey(type: T, name: name);

    log('Registering object with $dependencyKey');

    if (isRegistered<T>() && !allowReassignment) {
      throw WeaverException(
        'Cannot register object of $dependencyKey because there is an instance already registered',
      );
    }

    if (_dependencyMap.containsKey(dependencyKey)) {
      final dependency = (_dependencyMap.find(dependencyKey)! as Dependency<T>);
      dependency.value = null;
      dependency.lazyInstantiateCallback = callback;
    } else {
      _dependencyMap.set(dependencyKey, Dependency<T>.lazy(callback));
    }

    notifyObservers();
  }

  /// Retrieves a registered dependency of type [T] (and optionally [name]).
  ///
  /// Throws a [WeaverException] if the dependency is not registered.
  T get<T extends Object>({final String? name}) {
    final dependencyKey = DependencyKey(type: T, name: name);
    if (isRegistered<T>(name: name)) {
      final dependency = _dependencyMap.find(dependencyKey)! as Dependency<T>;
      if (dependency.value == null && dependency.lazyInstantiateCallback != null) {
        dependency.value = dependency.lazyInstantiateCallback!();
      }

      return dependency.value!;
    } else {
      var message = 'There is no instance of $dependencyKey registered.';

      final matchKeyForOnlyType = _dependencyMap.entries.map((final entry) {
        final key = entry.key;
        final registeredValue = entry.value.value;
        if (key.type == T && key.name != null && registeredValue != null) {
          return key;
        } else {
          return null;
        }
      }).nonNulls;

      if (matchKeyForOnlyType.isNotEmpty) {
        message = '$message But there are named dependencies registered with this type: $matchKeyForOnlyType. '
            'To retrieve named registered named objects you must pass both type & name when calling weaver.get()';
      }

      throw WeaverException(message);
    }
  }

  /// Asynchronously retrieves a registered dependency of type [T] (and optionally [name]).
  ///
  /// If the dependency is not yet registered, it returns a [Future] that completes
  /// when the dependency is registered.
  Future<T> getAsync<T extends Object>({final String? name}) async {
    if (isRegistered<T>(name: name)) {
      return get<T>(name: name);
    } else {
      final dependencyKey = DependencyKey(type: T, name: name);
      if (!_dependencyMap.containsKey(dependencyKey)) {
        _dependencyMap.set(dependencyKey, Dependency<T>.placeHolder());
      }

      return (_dependencyMap.find(dependencyKey)! as Dependency<T>).completer.future;
    }
  }

  /// Removes all dependency objects registered under the given [session] name.
  void clearSession(final String session) {
    _dependencyMap.removeBySession(session);
  }

  /// Returns true if the [Weaver] has entered the scope with the given [scopeName].
  bool isInScope(final String scopeName) => scopes.firstWhereOrNull((final e) => e.name == scopeName) != null;

  /// Signals that the application has entered the given [scope].
  ///
  /// This will notify all registered [SingleScopeHandler]s to handle the scope entry.
  /// Throws a [WeaverException] if the scope is already entered or if no handler
  /// is available for the scope.
  Future<void> enterScope(final Scope scope) async {
    if (isInScope(scope.name)) {
      throw WeaverException(
        'Has already entered scope <${scope.name}>, '
        'cannot call method weaver.enterScope on this scope again',
      );
    }

    final noHandlerAvailableToHandle =
        _scopeHandlers.where((final handler) => handler.canHandleScope(scope.name)).isEmpty;
    if (noHandlerAvailableToHandle) {
      throw WeaverException(
        'Entered scope ${scope.name} but there is no scope handler to handle this scope. '
        'please register a ScopeHandler class that handles scope: ${scope.name} using addScopeHandler() method.',
      );
    }

    // make scope handlers to handle the change in scopes (new scope added)
    for (final scopeHandler in _scopeHandlers) {
      await scopeHandler.handle(EnterScope(scope));
    }

    notifyObservers();
  }

  /// Signals that the application has left the scope with the given [scopeName].
  ///
  /// This will notify all registered [SingleScopeHandler]s to handle the scope exit.
  Future<void> leaveScope(final String scopeName) async {
    for (final scopeHandler in _scopeHandlers) {
      await scopeHandler.handle(LeaveScope(scopeName: scopeName));
    }
    notifyObservers();
  }

  /// Adds a [SingleScopeHandler] to this [Weaver] instance.
  ///
  /// The handler will be immediately notified to handle the current scope state.
  Future<void> addScopeHandler(final SingleScopeHandler newHandler) async {
    final hasConflictWithAnotherHandler =
        _scopeHandlers.firstWhereOrNull((final handler) => handler.canHandleScope(newHandler.scopeName)) != null;

    if (hasConflictWithAnotherHandler && !allowReassignment) {
      throw WeaverException('Cannot add ScopeHandler with name ${newHandler.scopeName}, since one is already added');
    } else if (allowReassignment) {
      _scopeHandlers.removeWhere((final currentHandler) => currentHandler.scopeName == newHandler.scopeName);
    }

    _scopeHandlers.add(newHandler);
  }

  /// Removes the [SingleScopeHandler] that handles the scope with [scopeName].
  ///
  /// Note: This does not leave the scope itself; use [leaveScope] for that.
  Future<void> removeScopeHandler(final String scopeName) async {
    final handler = _scopeHandlers.firstWhereOrNull((final handler) => handler.canHandleScope(scopeName));

    if (handler != null) {
      _scopeHandlers.removeWhere((final e) => e.canHandleScope(scopeName));

      // not calling handler.handle since the scope might not be left yet.
      // ??
      await handler.clearAllRegisteredObjects();
      handler.dispose();
    }
  }

  /// Clears all registered dependencies, active scopes, and scope handlers.
  void reset() {
    _dependencyMap.clear();
    for (final handler in _scopeHandlers) {
      handler.dispose();
    }
    _scopeHandlers.clear();
  }
}

class WeaverException implements Exception {
  WeaverException(this.message);

  final String message;

  @override
  String toString() => '\n\n⛔ $message';
}
