// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by weaver_builder

import 'package:example/person.dart';
import 'package:example/model.dart';

class GeneratedToStringMethods {
  static String personToString(Person obj) {
    return 'Person(firstName: ${obj.firstName}, lastName: ${obj.lastName}, age: ${obj.age}, isActive: ${obj.isActive})';
  }

  static String modelToString(Model obj) {
    return 'Model(name: ${obj.name}, age: ${obj.age})';
  }
}
