builders:
  weaver:
    import: "package:weaver_builder/weaver_builder.dart"
    builder_factories: ["weaverBuilder"]
    build_extensions:
      ".dart": [".weaver.dart"]
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        - "lib/**"

