builders:
  weaver:
    import: "package:weaver_builder/weaver_builder.dart"
    builder_factories: ["weaverBuilder"]
    build_extensions:
      ".dart": [".weaver.dart"]
    auto_apply: dependents
    build_to: source
    # applies_builders:
      # - source_gen|combining_builder    
    # defaults:
    #   generate_for:
    #     - "lib/**"

